--- udisks-glue-1.1.1-orig/Makefile	2010-10-22 09:12:46.916937704 +0200
+++ udisks-glue-1.1.1/Makefile	2010-10-22 09:21:49.193306433 +0200
@@ -1,4 +1,4 @@
-VERSION=$(shell git describe --tags --abbrev=0)
+VERSION=1.1.1
 
 INSTALL=install
 PREFIX=/usr
@@ -18,23 +18,22 @@
 CFLAGS+=$(shell pkg-config --cflags dbus-glib-1)
 CFLAGS+=$(shell pkg-config --cflags glib-2.0)
 CFLAGS+=$(shell pkg-config --cflags libconfuse)
+CFLAGS+=$(MYCFLAGS)
 LDFLAGS+=$(shell pkg-config --libs dbus-glib-1)
 LDFLAGS+=$(shell pkg-config --libs glib-2.0)
 LDFLAGS+=$(shell pkg-config --libs libconfuse)
+LDFLAGS+=$(MYLDFLAGS)
 
 .PHONY: all install clean distclean
 all: $(BIN)
 
 $(BIN): $(OBJS)
-	@echo "LD $<" && \
 	$(CC) $(LDFLAGS) -o $(BIN) $(OBJS)
 
 src/%.o: src/%.c $(HEADERS)
-	@echo "CC $<" && \
 	$(CC) $(CFLAGS) -c -o $@ $<
 
 $(BIN).1: man/$(BIN).1.roff
-	@echo "NROFF $<" && \
 	nroff -t man $< >$(BIN).1
 
 install: all
